kind: pipeline
name: devicelinks-build
type: docker

platform:
  os: linux
  arch: arm64

volumes:
  - name: cache
    host:
      path: /usr/local/docker/maven/.m2
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: common-run-env
    host:
      path: /usr/local/docker/devicelinks/run.env
  - name: device-center-env
    host:
      path: /usr/local/docker/devicelinks/device-center.env

steps:
  # Package SourceCode
  - name: package
    image: maven:3.9.9-eclipse-temurin-21-alpine
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean package -U -Dmaven.test.skip=true -Dmaven.repo.local=/root/.m2/repository

  # Build Console Docker Image
  - name: build console
    image: plugins/docker
    network_mode: host
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      dockerfile: build/docker/Dockerfile.develop.console
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/devicelinks/console
    volumes:
      - name: docker
        path: /var/run/docker.sock

  # Build Device-Center Docker Image
  - name: build device-center
    image: plugins/docker
    network_mode: host
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      dockerfile: build/docker/Dockerfile.develop.device-center
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/devicelinks/device-center
    volumes:
      - name: docker
        path: /var/run/docker.sock

  # Build Rule-Engine Docker Image
  - name: build rule-engine
    image: plugins/docker
    network_mode: host
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      dockerfile: build/docker/Dockerfile.develop.rule-engine
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/devicelinks/rule-engine
    volumes:
      - name: docker
        path: /var/run/docker.sock

  # Deploy Console
  - name: deploy console
    image: appleboy/drone-ssh
    network_mode: host
    settings:
      host:
        - 10.147.17.17
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - /usr/local/bin/docker stop devicelinks-console
        - /usr/local/bin/docker rm devicelinks-console
        - /usr/local/bin/docker image rm -f $(/usr/local/bin/docker image ls registry.cn-hangzhou.aliyuncs.com/devicelinks/console | awk 'NR>1{print $3}')
        - /usr/local/bin/docker pull registry.cn-hangzhou.aliyuncs.com/devicelinks/console:latest
        - /usr/local/bin/docker run -p 13650:13650 -d --restart=always --net=devicelinks --ip=172.10.1.10 --name devicelinks-console --env-file /usr/local/docker/devicelinks/run.env registry.cn-hangzhou.aliyuncs.com/devicelinks/console:latest

  # Deploy Device-Center
  - name: deploy device-center
    image: appleboy/drone-ssh
    network_mode: host
    settings:
      host:
        - 10.147.17.17
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - /usr/local/bin/docker stop devicelinks-device-center
        - /usr/local/bin/docker rm devicelinks-device-center
        - /usr/local/bin/docker image rm -f $(/usr/local/bin/docker image ls registry.cn-hangzhou.aliyuncs.com/devicelinks/device-center | awk 'NR>1{print $3}')
        - /usr/local/bin/docker pull registry.cn-hangzhou.aliyuncs.com/devicelinks/device-center:latest
        - /usr/local/bin/docker run -p 13651:13651 -d --restart=always --net=devicelinks --ip=172.10.1.11 --name devicelinks-device-center --env-file /usr/local/docker/devicelinks/run.env --env-file /usr/local/docker/devicelinks/device-center.env registry.cn-hangzhou.aliyuncs.com/devicelinks/device-center:latest

  # Deploy Rule-Engine
  - name: deploy rule-engine
    image: appleboy/drone-ssh
    network_mode: host
    settings:
      host:
        - 10.147.17.17
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - /usr/local/bin/docker stop devicelinks-rule-engine
        - /usr/local/bin/docker rm devicelinks-rule-engine
        - /usr/local/bin/docker image rm -f $(/usr/local/bin/docker image ls registry.cn-hangzhou.aliyuncs.com/devicelinks/rule-engine | awk 'NR>1{print $3}')
        - /usr/local/bin/docker pull registry.cn-hangzhou.aliyuncs.com/devicelinks/rule-engine:latest
        - /usr/local/bin/docker run -p 13652:13652 -d --restart=always --net=devicelinks --ip=172.10.1.12 --name devicelinks-rule-engine --env-file /usr/local/docker/devicelinks/run.env registry.cn-hangzhou.aliyuncs.com/devicelinks/rule-engine:latest

  # Deploy Transport-Http
  - name: deploy transport-http
    image: appleboy/drone-ssh
    network_mode: host
    settings:
      host:
        - 10.147.17.17
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 5m
      script:
        - /usr/local/bin/docker stop devicelinks-transport-http
        - /usr/local/bin/docker rm devicelinks-transport-http
        - /usr/local/bin/docker image rm -f $(/usr/local/bin/docker image ls registry.cn-hangzhou.aliyuncs.com/devicelinks/transport-http | awk 'NR>1{print $3}')
        - /usr/local/bin/docker pull registry.cn-hangzhou.aliyuncs.com/devicelinks/transport-http:latest
        - /usr/local/bin/docker run -p 15001:15001 -d --restart=always --net=devicelinks --ip=172.10.1.13 --name devicelinks-transport-http --env-file /usr/local/docker/devicelinks/run.env registry.cn-hangzhou.aliyuncs.com/devicelinks/transport-http:latest

trigger:
  branch:
    - master
  event:
    - push