kind: pipeline
name: devicelinks-build
type: docker

platform:
  os: linux
  arch: arm64
volumes:
  - name: maven-cache
    host:
      path: /usr/local/docker/maven/.m2
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: env-file
    host:
      path: /usr/local/docker/devicelinks/run.env
steps:
  # Package SourceCode
  - name: package
    image: maven:3.9.9-eclipse-temurin-21-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - mvn clean package -U -Dmaven.test.skip=true -Dmaven.repo.local=/root/.m2/repository

  # Build Console Docker Image
  - name: build console docker image
    image: plugins/docker
    network_mode: host
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      dockerfile: build/docker/Dockerfile.develop.console
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/devicelinks/console
    volumes:
      - name: docker
        path: /var/run/docker.sock

  # Build Core-Service Docker Image
  - name: build core-service docker image
    image: plugins/docker
    network_mode: host
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
      dockerfile: build/docker/Dockerfile.develop.core-service
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/devicelinks/core-service
    volumes:
      - name: docker
        path: /var/run/docker.sock

  # Deploy Console
  - name: deploy console
    image: appleboy/drone-ssh
    network_mode: host
    settings:
      host:
        - 127.0.0.1
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      script:
        - docker stop devicelinks-console
        - docker rm devicelinks-console
        - docker image rm -f $(docker image ls registry.cn-hangzhou.aliyuncs.com/devicelinks/console | awk 'NR>1{print $3}')
        - docker pull registry.cn-hangzhou.aliyuncs.com/devicelinks/console:latest
        - docker run -p 13650:13650 -d --name devicelinks-console --env-file /root/run.env registry.cn-hangzhou.aliyuncs.com/devicelinks/console:latest
    volumes:
      # 挂载环境变量文件
      - name: env-file
        path: /root/run.env

trigger:
  branch:
    - master
  event:
    - push