server:
  port: 13651
  ssl:
    enabled: true
    key-store: classpath:ssl/server.jks
    key-store-password: fZjLaxFgt5Txs7qSF5od
    key-store-type: JKS
    key-alias: server
    # 服务端证书信任库
    trust-store: classpath:ssl/truststore.jks
    trust-store-password: fZjLaxFgt5Txs7qSF5od
    # 开启双向认证
    client-auth: need
    trust-store-type: JKS
spring:
  main:
    allow-circular-references: true
  profiles:
    active: develop
devicelinks:
  center:
    version: @project.version@

logging:
  # 多环境下的日志配置
  config: classpath:logback-${spring.profiles.active}.xml