server:
  port: 13650
spring:
  main:
    allow-circular-references: true
  profiles:
    active: develop

devicelinks:
  console:
    version: @project.version@

logging:
  # 多环境下的日志配置
  config: classpath:logback-${spring.profiles.active}.xml