spring:
  datasource:
    url: jdbc:mysql://10.147.17.17:3306/devicelinks
    username: root
    password: AZGv2RQCXRYyJWgo4bjb
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 10.147.17.17
      database: 2
      password: homeserver@2025

devicelinks:
  # 应用服务配置
  console:
    token:
      expires-seconds: 7200
  # 服务初始化配置
  initializer:
    # 初始化数据库
    database:
      initializer-away: check
      check-init-tables-count-sql: "select count(table_name) from information_schema.tables where table_schema = '%s'"
      schema-name: devicelinks
      schema-sql: classpath:init-schema.sql
      data-sql: classpath:init-data.sql

logging:
  level:
    cn.devicelinks.jdbc: debug